agent:
  name: rfdetr_export
  description: Agent responsible for exporting a fine-tuned RF-DETR model to ONNX format

templates:
  - template_name: InputTemplate
    class_name: InputTemplate
    attributes: {}

  - template_name: RFDETRExport
    class_name: RFDETRExport
    template_input: InputTemplate
    attributes:
      model_params:
        pretrain_weights: checkpoint_best_total.pth