agent:
  name: rfdetr_inference_trained
  description: Agent that runs inferences on a dataset with a fine-tuned RF-DETR model

templates:
  - template_name: InputTemplate
    class_name: InputTemplate
    attributes: {}

  - template_name: FolderImageDatasetCV2
    class_name: FolderImageDatasetCV2
    template_input: InputTemplate
    attributes:
      data_dir: datasets/COCO Dataset.v37i.coco

  - template_name: RFDETRInference
    class_name: RFDETRInference
    template_input: FolderImageDatasetCV2
    attributes:
      threshold: 0.5
      annotations_path: datasets/COCO Dataset.v37i.coco/test/_annotations.coco.json
      model_params:
        pretrain_weights: checkpoint_best_total.pth
        num_classes: 34

  - template_name: BBoxDrawer
    class_name: BBoxDrawer
    template_input: RFDETRInference
    attributes:
      draw_confidence: True
      randomized_color: False
      overwrite: True

  - template_name: ImageSaver
    class_name: ImageSaver
    template_input: BBoxDrawer
    attributes:
      save_dir: rfdetr/output
      extension: png