agent:
  name: segment_predict
  description: agent to run inference on an image using a segmentation model with Ultralytics


templates:
- template_name: InputTemplate-1
  class_name: InputTemplate
  attributes: {}

- template_name: UltralyticsPredict
  class_name: UltralyticsPredict
  template_input: InputTemplate-1
  attributes:
    model_class: YOLO
    model: yolo11n-seg.pt
    task: segment
    verbose: 0
    predict_params: {}

- template_name: BBoxDrawer
  class_name: BBoxDrawer
  template_input: UltralyticsPredict
  attributes: {}

- template_name: SegmentationMaskDrawer
  class_name: SegmentationMaskDrawer
  template_input: BBoxDrawer
  attributes: {}
