agent:
  name: predict_obb
  description: agent to run inference on an image using a OBB model with Ultralytics


templates:
- template_name: InputTemplate-1
  class_name: InputTemplate
  attributes: {}

- template_name: UltralyticsPredict
  class_name: UltralyticsPredict
  template_input: InputTemplate-1
  attributes:
    model_class: YOLO
    model: yolo11n-obb.pt
    task: obb
    verbose: 0
    predict_params: {}

- template_name: BBoxDrawer
  class_name: BBoxDrawer
  template_input: UltralyticsPredict
  attributes: {}

- template_name: OrientedBBoxDrawer
  class_name: OrientedBBoxDrawer
  template_input: BBoxDrawer
  attributes: {}
