agent:
  name: predict_pose
  description: agent to run inference on an image using a Pose detection model with Ultralytics

templates:
- template_name: InputTemplate-1
  class_name: InputTemplate
  attributes: {}

- template_name: UltralyticsPredict
  class_name: UltralyticsPredict
  template_input: InputTemplate-1
  attributes:
    model_class: YOLO
    model: yolo11n-pose.pt
    task: pose
    verbose: 0
    predict_params: {}

- template_name: BBoxDrawer
  class_name: BBoxDrawer
  template_input: UltralyticsPredict
  attributes: {}

- template_name: KeyPointsDrawer
  class_name: KeyPointsDrawer
  template_input: BBoxDrawer
  attributes: {}
